CREATE DATABASE Pizzeria

use Pizzeria

CREATE TABLE CustomerAccount(
	Id INT IDENTITY(1,1) CONSTRAINT PK_CustomerAccount PRIMARY KEY,
	Login NVARCHAR(20) UNIQUE,
	Password NVARCHAR(20),
	Balance NUMERIC,
)

CREATE TABLE "Order"(
	Id INT IDENTITY(1,1) CONSTRAINT PK_Order PRIMARY KEY,
	CustomerId INT CONSTRAINT FK_OrderCustumer REFERENCES CustomerAccount(Id) ON DELETE CASCADE,
	TimeOrder DATETIME
)

CREATE TABLE Product(
	Id INT IDENTITY(1,1) CONSTRAINT PK_Product PRIMARY KEY,
	Name NVARCHAR(20),
	Price NUMERIC
)

CREATE TABLE OrderProduct(
	OrderId INT CONSTRAINT FK_OrderId REFERENCES "Order"(Id)  ON DELETE CASCADE,
	ProductId INT CONSTRAINT FK_ProductId REFERENCES Product(Id),
)